name: WildFly EE 9 CI Testing

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  build-all:
    name: Compile (no tests) with JDK 8
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: AdoptOpenJDK/install-jdk@v1
      name: Install JDK 8
      with:
        version: 8    
    - name: Build
      run: |
        mvn -U -B -DskipTests -Drelease install
    - name: Tar Maven Repo
      shell: bash
      run: tar -czf maven-repo.tgz -C ~ .m2/repository
    - name: Persist Maven Repo
      uses: actions/upload-artifact@v1
      with:
        name: maven-repo
        path: maven-repo.tgz
    - uses: actions/upload-artifact@v2
      if: failure()
      with:
        name: surefire-reports-build
        path: '**/surefire-reports/*.txt'
  test-matrix:
    name: ${{ matrix.profile }}-${{ matrix.openjdk_impl}}-${{ matrix.jdk }}-${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    needs: build-all
    strategy:
      fail-fast: false
      matrix:
        profile: [ts.ee9, ts.layers]
        os: [ubuntu-20.04, windows-latest]
        jdk: [8, 11, 14]
        openjdk_impl: [hotspot]
    steps:
    - name: Configure runner - Linux 
      if: contains(matrix.os, 'ubuntu')
      run: |
        sudo bash -c "echo '127.0.0.1   localhost localhost.localdomain localhost4 localhost4.localdomain4' > /etc/hosts"
        sudo bash -c "echo '::1         localhost localhost.localdomain localhost6 localhost6.localdomain6' >> /etc/hosts"
    - name: Configure Runner - Windows
      if: contains(matrix.os, 'windows')
      run: |
        echo '127.0.0.1   localhost localhost.localdomain localhost4 localhost4.localdomain4' > %SystemRoot%\System32\drivers\etc\hosts
        echo '::1         localhost localhost.localdomain localhost6 localhost6.localdomain6' >> %SystemRoot%\System32\drivers\etc\hosts
      shell: cmd
    - uses: actions/checkout@v2
    - name: Download Maven Repo
      uses: actions/download-artifact@v1
      with:
        name: maven-repo
        path: .
    - name: Extract Maven Repo
      shell: bash
      run: tar -xzf maven-repo.tgz -C ~
    - name: Set up JDK ${{ matrix.java }}
      uses: AdoptOpenJDK/install-jdk@v1
      with:
        version: ${{ matrix.jdk }}
        impl: ${{ matrix.jdk_impl }}
    - name: Run Tests
      run: mvn -U -B -fae test --define=${{ matrix.profile }}
    - uses: actions/upload-artifact@v2
      if: failure()
      with:
        name: surefire-reports-${{ matrix.profile }}-${{ matrix.openjdk_impl}}-${{ matrix.jdk }}-${{ matrix.os }}
        path: '**/surefire-reports/*.txt'